import {apiError,ensureDatabase,getSessionUser,platformEnv,requireVtcPermission} from "@/lib/platform";
export async function GET(request:Request){
 await ensureDatabase();const user=await getSessionUser(request);if(!user)return apiError("Anmeldung erforderlich",401);const db=platformEnv().DB,url=new URL(request.url),requested=url.searchParams.get("vtcId");
 const vtc=await db.prepare(`SELECT v.id,v.name,v.tag,v.slug,r.name AS roleName,r.rank FROM memberships m JOIN vtcs v ON v.id=m.vtc_id LEFT JOIN roles r ON r.id=m.role_id WHERE m.user_id=? AND m.status='active' AND (? IS NULL OR v.id=?) ORDER BY r.rank DESC,v.name LIMIT 1`).bind(user.id,requested,requested).first<any>();
 if(!vtc)return apiError("Diesem Benutzer ist noch keine Spedition zugeordnet",404);const actor=await requireVtcPermission(request,vtc.id,"view_dashboard");if(!actor)return apiError("Dashboardrecht erforderlich",403);const canViewFinance=actor.permissions.includes("*")||actor.permissions.includes("manage_payroll");
 const [drivers,online,probation,applications,today,month,finance,events,trips]=await Promise.all([
  db.prepare(`SELECT COUNT(*) count FROM memberships WHERE vtc_id=? AND status='active'`).bind(vtc.id).first<any>(),db.prepare(`SELECT COUNT(DISTINCT user_id) count FROM telemetry WHERE vtc_id=? AND recorded_at>=datetime('now','-15 minutes')`).bind(vtc.id).first<any>(),db.prepare(`SELECT COUNT(*) count FROM personnel_records WHERE vtc_id=? AND status='probation'`).bind(vtc.id).first<any>(),db.prepare(`SELECT COUNT(*) count FROM applications WHERE vtc_id=? AND status IN ('received','precheck','assigned','questions','interview','test_drive','waitlist')`).bind(vtc.id).first<any>(),db.prepare(`SELECT COUNT(*) count,COALESCE(SUM(distance_km),0) km FROM trips WHERE vtc_id=? AND date(started_at)=date('now')`).bind(vtc.id).first<any>(),db.prepare(`SELECT COUNT(*) count,COALESCE(SUM(distance_km),0) km,COALESCE(AVG(damage),0) damage,COALESCE(AVG(CASE WHEN distance_km>0 THEN fuel_liters*100.0/distance_km END),0) consumption FROM trips WHERE vtc_id=? AND strftime('%Y-%m',started_at)=strftime('%Y-%m','now')`).bind(vtc.id).first<any>(),canViewFinance?db.prepare(`SELECT COALESCE(SUM(CASE WHEN e.amount_cents>0 AND e.status='posted' THEN e.amount_cents ELSE 0 END),0) income,COALESCE(ABS(SUM(CASE WHEN e.amount_cents<0 AND e.status='posted' THEN e.amount_cents ELSE 0 END)),0) expenses FROM finance_entries e JOIN finance_accounts a ON a.id=e.account_id WHERE a.vtc_id=?`).bind(vtc.id).first<any>():Promise.resolve({income:0,expenses:0}),db.prepare(`SELECT COUNT(*) count FROM events WHERE vtc_id=? AND starts_at>=CURRENT_TIMESTAMP`).bind(vtc.id).first<any>(),db.prepare(`SELECT t.id,u.display_name AS driver,t.source_city AS sourceCity,t.destination_city AS destinationCity,t.distance_km AS distanceKm,t.status,t.started_at AS startedAt FROM trips t LEFT JOIN users u ON u.id=t.user_id WHERE t.vtc_id=? ORDER BY t.started_at DESC LIMIT 8`).bind(vtc.id).all<any>()
 ]);
 return Response.json({user:{id:user.id,displayName:user.displayName},vtc,rights:{canViewFinance},metrics:{drivers:Number(drivers?.count||0),online:Number(online?.count||0),probation:Number(probation?.count||0),applications:Number(applications?.count||0),todayTrips:Number(today?.count||0),todayKm:Number(today?.km||0),monthTrips:Number(month?.count||0),monthKm:Number(month?.km||0),damage:Number(month?.damage||0),consumption:Number(month?.consumption||0),income:Number(finance?.income||0),expenses:Number(finance?.expenses||0),events:Number(events?.count||0)},trips:trips.results});
}
