import { discordRequest, rulesMessage } from "@/lib/discord";
import { apiError, audit, ensureDatabase, platformEnv, randomId, requireFounder } from "@/lib/platform";

const clean = (value: unknown, max = 500) => String(value ?? "").trim().slice(0, max);
export async function GET(request: Request) {
  await ensureDatabase(); const founder = await requireFounder(request); if (!founder) return apiError("Gründerzugang erforderlich", 403); const db = platformEnv().DB;
  const guilds = await db.prepare(`SELECT g.guild_id AS guildId,g.vtc_id AS vtcId,g.welcome_channel_id AS welcomeChannelId,g.welcome_message AS welcomeMessage,g.announcement_channel_id AS announcementChannelId,g.ticket_category_id AS ticketCategoryId,g.support_role_id AS supportRoleId,g.auto_role_ids AS autoRoleIds,g.enabled,b.display_name AS displayName,b.welcome_image_url AS welcomeImageUrl,b.announcement_image_url AS announcementImageUrl,b.rules_channel_id AS rulesChannelId,b.rules_title AS rulesTitle,b.rules_description AS rulesDescription,b.rules_image_url AS rulesImageUrl,b.rules_confirm_role_id AS rulesConfirmRoleId,b.rules_button_label AS rulesButtonLabel,b.rules_message_id AS rulesMessageId,b.delivery_channel_id AS deliveryChannelId FROM discord_guilds g LEFT JOIN discord_guild_branding b ON b.guild_id=g.guild_id ORDER BY g.updated_at DESC`).all();
  const rules = await db.prepare(`SELECT id,guild_id AS guildId,title,body,position,active FROM bot_rules ORDER BY guild_id,position`).all(); return Response.json({ guilds: guilds.results, rules: rules.results });
}
export async function POST(request: Request) {
  await ensureDatabase(); const founder = await requireFounder(request); if (!founder) return apiError("Gründerzugang erforderlich", 403); const body = await request.json() as Record<string, any>, db = platformEnv().DB, action = body.action;
  if (action === "save" && body.guild) { const d = body.guild, guildId = clean(d.guildId, 30); if (!/^\d{17,20}$/.test(guildId)) return apiError("Gültige Discord-Server-ID erforderlich"); await db.batch([db.prepare(`INSERT INTO discord_guilds (guild_id,vtc_id,welcome_channel_id,welcome_message,announcement_channel_id,ticket_category_id,support_role_id,auto_role_ids,enabled,updated_by,updated_at) VALUES (?,?,?,?,?,?,?,?,1,?,CURRENT_TIMESTAMP) ON CONFLICT(guild_id) DO UPDATE SET vtc_id=excluded.vtc_id,welcome_channel_id=excluded.welcome_channel_id,welcome_message=excluded.welcome_message,announcement_channel_id=excluded.announcement_channel_id,ticket_category_id=excluded.ticket_category_id,support_role_id=excluded.support_role_id,auto_role_ids=excluded.auto_role_ids,enabled=1,updated_by=excluded.updated_by,updated_at=CURRENT_TIMESTAMP`).bind(guildId,clean(d.vtcId,80)||null,clean(d.welcomeChannelId,30)||null,clean(d.welcomeMessage,1000)||"Willkommen {user} bei {vtc}!",clean(d.announcementChannelId,30)||null,clean(d.ticketCategoryId,30)||null,clean(d.supportRoleId,30)||null,JSON.stringify(String(d.autoRoleIds??"").split(",").map((x:string)=>x.trim()).filter(Boolean)),founder.id),db.prepare(`INSERT INTO discord_guild_branding (guild_id,display_name,welcome_image_url,rules_channel_id,rules_title,rules_description,rules_image_url,rules_confirm_role_id,rules_button_label,delivery_channel_id,announcement_image_url,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(guild_id) DO UPDATE SET display_name=excluded.display_name,welcome_image_url=excluded.welcome_image_url,rules_channel_id=excluded.rules_channel_id,rules_title=excluded.rules_title,rules_description=excluded.rules_description,rules_image_url=excluded.rules_image_url,rules_confirm_role_id=excluded.rules_confirm_role_id,rules_button_label=excluded.rules_button_label,delivery_channel_id=excluded.delivery_channel_id,announcement_image_url=excluded.announcement_image_url,updated_at=CURRENT_TIMESTAMP`).bind(guildId,clean(d.displayName,100)||null,clean(d.welcomeImageUrl,1000)||null,clean(d.rulesChannelId,30)||null,clean(d.rulesTitle,256)||"Regelwerk",clean(d.rulesDescription,4000)||null,clean(d.rulesImageUrl,1000)||null,clean(d.rulesConfirmRoleId,30)||null,clean(d.rulesButtonLabel,80)||"Regeln bestätigen",clean(d.deliveryChannelId,30)||null,clean(d.announcementImageUrl,1000)||null)]); await audit("discord.config.updated","discord_guild",guildId,founder.id,{vtcId:d.vtcId}); return Response.json({saved:true}); }
  if (action === "addRule" && body.guildId && clean(body.title, 180) && clean(body.body, 1000)) { const id=randomId(); await db.prepare(`INSERT INTO bot_rules (id,guild_id,title,body,position) VALUES (?,?,?,?,?)`).bind(id,clean(body.guildId,30),clean(body.title,180),clean(body.body,1000),Number(body.position??0)).run(); return Response.json({saved:true,id}); }
  if (action === "publishRules" && body.guildId) { const guildId=clean(body.guildId,30), config=await db.prepare(`SELECT b.*,b.guild_id AS guildId FROM discord_guild_branding b JOIN discord_guilds g ON g.guild_id=b.guild_id WHERE b.guild_id=? AND g.enabled=1`).bind(guildId).first<Record<string,unknown>>(), rules=await db.prepare(`SELECT title,body FROM bot_rules WHERE guild_id=? AND active=1 ORDER BY position`).bind(guildId).all<{title:string;body:string}>(); if (!config?.rules_channel_id) return apiError("Regelkanal fehlt",409); const sent=await discordRequest<{id:string}>(`/channels/${config.rules_channel_id}/messages`,{method:"POST",body:JSON.stringify(rulesMessage({guildId,rulesTitle:config.rules_title,rulesDescription:config.rules_description,rulesImageUrl:config.rules_image_url,rulesButtonLabel:config.rules_button_label},rules.results))}); await db.prepare(`UPDATE discord_guild_branding SET rules_message_id=?,updated_at=CURRENT_TIMESTAMP WHERE guild_id=?`).bind(sent?.id??null,guildId).run(); return Response.json({sent:true}); }
  if (action === "announce" && body.guildId && clean(body.message,4000)) { const config=await db.prepare(`SELECT g.announcement_channel_id AS channelId,b.announcement_image_url AS imageUrl FROM discord_guilds g LEFT JOIN discord_guild_branding b ON b.guild_id=g.guild_id WHERE g.guild_id=? AND g.enabled=1`).bind(clean(body.guildId,30)).first<{channelId:string|null;imageUrl:string|null}>(); if(!config?.channelId)return apiError("Ankündigungskanal fehlt",409); const embed:any={description:clean(body.message,4000),color:0x5865f2};const image=clean(body.imageUrl,1000)||config.imageUrl||"";if(/^https:\/\//i.test(image))embed.image={url:image};await discordRequest(`/channels/${config.channelId}/messages`,{method:"POST",body:JSON.stringify({embeds:[embed],allowed_mentions:{parse:[]}})});return Response.json({sent:true}); }
  return apiError("Ungültige Discord-Adminaktion");
}
