#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <winsock2.h>
#include <windows.h>
#include <algorithm>
#include <cstdint>
#include <sstream>
#include <string>
#include <cstring>
#include "scssdk_telemetry.h"
#include "common/scssdk_telemetry_common_channels.h"
#include "common/scssdk_telemetry_common_configs.h"
#include "common/scssdk_telemetry_common_gameplay_events.h"
#include "common/scssdk_telemetry_truck_common_channels.h"
#include "common/scssdk_telemetry_trailer_common_channels.h"
#include "eurotrucks2/scssdk_eut2.h"
#include "amtrucks/scssdk_ats.h"

namespace {
struct State {
  std::string game="ETS2",event,job_key,truck,cargo,source_city,source_company,destination_city,destination_company;
  double x=0,y=0,z=0,heading=0;
  float speed=0,rpm=0,fuel=0,fuel_average=0,fuel_range=0,cruise=0,navigation_distance=0,navigation_time=0,navigation_speed_limit=0,odometer=0,cargo_mass=0,planned_distance=0,brake_air_pressure=0,water_temperature=0,battery_voltage=0,input_steering=0,input_throttle=0,input_brake=0,wear_engine=0,wear_transmission=0,wear_cabin=0,wear_chassis=0,wear_wheels=0,trailer_body=0,trailer_chassis=0,trailer_wheels=0,trailer_cargo_damage=0;
  int gear=0,retarder_level=0;scs_u32_t game_time=0;bool engine=false,parking_brake=false,motor_brake=false,left_blinker=false,right_blinker=false,hazard=false,low_beam=false,high_beam=false,beacon=false,has_job=false;std::int64_t income=0;
} state;
SOCKET udp_socket=INVALID_SOCKET;sockaddr_in endpoint{};ULONGLONG last_send=0;scs_log_t game_log=nullptr;

std::string escape(const std::string& value){std::string out;out.reserve(value.size()+8);for(char c:value){switch(c){case '\\':out+="\\\\";break;case '"':out+="\\\"";break;case '\n':out+="\\n";break;case '\r':break;default:if(static_cast<unsigned char>(c)>=32)out+=c;}}return out;}
std::string text(const scs_named_value_t* attrs,const char* name){for(auto p=attrs;p&&p->name;++p)if(std::strcmp(p->name,name)==0&&p->value.type==SCS_VALUE_TYPE_string)return p->value.value_string.value?p->value.value_string.value:"";return {};}
double number(const scs_named_value_t* attrs,const char* name){for(auto p=attrs;p&&p->name;++p)if(std::strcmp(p->name,name)==0){switch(p->value.type){case SCS_VALUE_TYPE_float:return p->value.value_float.value;case SCS_VALUE_TYPE_double:return p->value.value_double.value;case SCS_VALUE_TYPE_u32:return p->value.value_u32.value;case SCS_VALUE_TYPE_s32:return p->value.value_s32.value;case SCS_VALUE_TYPE_u64:return static_cast<double>(p->value.value_u64.value);case SCS_VALUE_TYPE_s64:return static_cast<double>(p->value.value_s64.value);default:return 0;}}return 0;}
void send_packet(const char* forced_event=nullptr){if(udp_socket==INVALID_SOCKET)return;const double truck_damage=std::max({state.wear_engine,state.wear_transmission,state.wear_cabin,state.wear_chassis,state.wear_wheels}),trailer_damage=std::max({state.trailer_body,state.trailer_chassis,state.trailer_wheels,state.trailer_cargo_damage});std::ostringstream j;j<<"{\"game\":\""<<state.game<<"\",\"event\":"<<(forced_event?"\""+escape(forced_event)+"\"":state.event.empty()?"null":"\""+escape(state.event)+"\"")<<",\"jobKey\":\""<<escape(state.job_key)<<"\",\"worldX\":"<<state.x<<",\"worldY\":"<<state.y<<",\"worldZ\":"<<state.z<<",\"heading\":"<<state.heading<<",\"speedKph\":"<<(state.speed*3.6)<<",\"rpm\":"<<state.rpm<<",\"gear\":"<<state.gear<<",\"fuel\":"<<state.fuel<<",\"fuelAverage\":"<<(state.fuel_average*100.0)<<",\"fuelRange\":"<<state.fuel_range<<",\"cruiseControl\":"<<(state.cruise>0?"true":"false")<<",\"engineEnabled\":"<<(state.engine?"true":"false")<<",\"parkingBrake\":"<<(state.parking_brake?"true":"false")<<",\"motorBrake\":"<<(state.motor_brake?"true":"false")<<",\"retarderLevel\":"<<state.retarder_level<<",\"leftBlinker\":"<<(state.left_blinker?"true":"false")<<",\"rightBlinker\":"<<(state.right_blinker?"true":"false")<<",\"hazardWarning\":"<<(state.hazard?"true":"false")<<",\"lowBeam\":"<<(state.low_beam?"true":"false")<<",\"highBeam\":"<<(state.high_beam?"true":"false")<<",\"beacon\":"<<(state.beacon?"true":"false")<<",\"brakeAirPressure\":"<<state.brake_air_pressure<<",\"waterTemperature\":"<<state.water_temperature<<",\"batteryVoltage\":"<<state.battery_voltage<<",\"steeringInput\":"<<state.input_steering<<",\"throttleInput\":"<<state.input_throttle<<",\"brakeInput\":"<<state.input_brake<<",\"navigationDistance\":"<<state.navigation_distance<<",\"navigationTime\":"<<state.navigation_time<<",\"navigationSpeedLimitKph\":"<<(state.navigation_speed_limit*3.6)<<",\"truckDamage\":"<<truck_damage<<",\"trailerDamage\":"<<trailer_damage<<",\"cargoDamage\":"<<state.trailer_cargo_damage<<",\"gameTime\":"<<state.game_time<<",\"odometer\":"<<state.odometer<<",\"truck\":\""<<escape(state.truck)<<"\",\"cargo\":\""<<escape(state.cargo)<<"\",\"cargoMass\":"<<state.cargo_mass<<",\"sourceCity\":\""<<escape(state.source_city)<<"\",\"sourceCompany\":\""<<escape(state.source_company)<<"\",\"destinationCity\":\""<<escape(state.destination_city)<<"\",\"destinationCompany\":\""<<escape(state.destination_company)<<"\",\"plannedDistanceKm\":"<<state.planned_distance<<",\"gameIncomeCents\":"<<(state.income*100)<<"}";const auto data=j.str();sendto(udp_socket,data.c_str(),static_cast<int>(data.size()),0,reinterpret_cast<sockaddr*>(&endpoint),sizeof(endpoint));state.event.clear();}

SCSAPI_VOID frame_end(scs_event_t,const void*,scs_context_t){const auto now=GetTickCount64();if(now-last_send>=250){last_send=now;send_packet();}}
SCSAPI_VOID store_float(scs_string_t,scs_u32_t,const scs_value_t* v,scs_context_t c){if(v&&v->type==SCS_VALUE_TYPE_float&&c)*static_cast<float*>(c)=v->value_float.value;}
SCSAPI_VOID store_double_as_float(scs_string_t,scs_u32_t,const scs_value_t* v,scs_context_t c){if(v&&c)*static_cast<double*>(c)=v->type==SCS_VALUE_TYPE_float?v->value_float.value:v->type==SCS_VALUE_TYPE_double?v->value_double.value:0;}
SCSAPI_VOID store_s32(scs_string_t,scs_u32_t,const scs_value_t* v,scs_context_t c){if(v&&v->type==SCS_VALUE_TYPE_s32&&c)*static_cast<int*>(c)=v->value_s32.value;}
SCSAPI_VOID store_u32(scs_string_t,scs_u32_t,const scs_value_t* v,scs_context_t c){if(v&&c)*static_cast<scs_u32_t*>(c)=v->type==SCS_VALUE_TYPE_u32?v->value_u32.value:static_cast<scs_u32_t>(v->value_u64.value);}
SCSAPI_VOID store_bool(scs_string_t,scs_u32_t,const scs_value_t* v,scs_context_t c){if(v&&v->type==SCS_VALUE_TYPE_bool&&c)*static_cast<bool*>(c)=v->value_bool.value!=0;}
SCSAPI_VOID store_placement(scs_string_t,scs_u32_t,const scs_value_t* v,scs_context_t){if(v&&v->type==SCS_VALUE_TYPE_dplacement){state.x=v->value_dplacement.position.x;state.y=v->value_dplacement.position.y;state.z=v->value_dplacement.position.z;state.heading=v->value_dplacement.orientation.heading*360.0;}}
SCSAPI_VOID configuration(scs_event_t,const void* info_ptr,scs_context_t){const auto* info=static_cast<const scs_telemetry_configuration_t*>(info_ptr);if(std::strcmp(info->id,SCS_TELEMETRY_CONFIG_job)!=0)return;const std::string old=state.job_key;state.cargo=text(info->attributes,SCS_TELEMETRY_CONFIG_ATTRIBUTE_cargo);state.cargo_mass=number(info->attributes,SCS_TELEMETRY_CONFIG_ATTRIBUTE_cargo_mass);state.source_city=text(info->attributes,SCS_TELEMETRY_CONFIG_ATTRIBUTE_source_city);state.source_company=text(info->attributes,SCS_TELEMETRY_CONFIG_ATTRIBUTE_source_company);state.destination_city=text(info->attributes,SCS_TELEMETRY_CONFIG_ATTRIBUTE_destination_city);state.destination_company=text(info->attributes,SCS_TELEMETRY_CONFIG_ATTRIBUTE_destination_company);state.income=static_cast<std::int64_t>(number(info->attributes,SCS_TELEMETRY_CONFIG_ATTRIBUTE_income));state.planned_distance=number(info->attributes,SCS_TELEMETRY_CONFIG_ATTRIBUTE_planned_distance_km);state.job_key=text(info->attributes,SCS_TELEMETRY_CONFIG_ATTRIBUTE_source_city_id)+"|"+text(info->attributes,SCS_TELEMETRY_CONFIG_ATTRIBUTE_source_company_id)+"|"+text(info->attributes,SCS_TELEMETRY_CONFIG_ATTRIBUTE_destination_city_id)+"|"+text(info->attributes,SCS_TELEMETRY_CONFIG_ATTRIBUTE_destination_company_id)+"|"+text(info->attributes,SCS_TELEMETRY_CONFIG_ATTRIBUTE_cargo_id)+"|"+std::to_string(static_cast<long long>(state.cargo_mass));state.has_job=!state.cargo.empty()||!state.source_city.empty();if(state.has_job&&state.job_key!=old)send_packet("job.started");}
SCSAPI_VOID gameplay(scs_event_t,const void* info_ptr,scs_context_t){const auto* info=static_cast<const scs_telemetry_gameplay_event_t*>(info_ptr);if(std::strcmp(info->id,SCS_TELEMETRY_GAMEPLAY_EVENT_job_delivered)==0){state.income=static_cast<std::int64_t>(number(info->attributes,SCS_TELEMETRY_GAMEPLAY_EVENT_ATTRIBUTE_revenue));send_packet("job.delivered");state.has_job=false;}else if(std::strcmp(info->id,SCS_TELEMETRY_GAMEPLAY_EVENT_job_cancelled)==0){send_packet("job.cancelled");state.has_job=false;}}
}

SCSAPI_RESULT scs_telemetry_init(const scs_u32_t version,const scs_telemetry_init_params_t* params){if(version!=SCS_TELEMETRY_VERSION_1_01)return SCS_RESULT_unsupported;const auto* p=static_cast<const scs_telemetry_init_params_v101_t*>(params);game_log=p->common.log;state.game=std::strcmp(p->common.game_id,SCS_GAME_ID_ATS)==0?"ATS":"ETS2";WSADATA data{};if(WSAStartup(MAKEWORD(2,2),&data)!=0)return SCS_RESULT_generic_error;udp_socket=socket(AF_INET,SOCK_DGRAM,IPPROTO_UDP);endpoint.sin_family=AF_INET;endpoint.sin_port=htons(35055);endpoint.sin_addr.s_addr=htonl(INADDR_LOOPBACK);p->register_for_event(SCS_TELEMETRY_EVENT_frame_end,frame_end,nullptr);p->register_for_event(SCS_TELEMETRY_EVENT_configuration,configuration,nullptr);p->register_for_event(SCS_TELEMETRY_EVENT_gameplay,gameplay,nullptr);
#define REG_FLOAT(channel,field) p->register_for_channel(channel,SCS_U32_NIL,SCS_VALUE_TYPE_float,SCS_TELEMETRY_CHANNEL_FLAG_none,store_float,&state.field)
REG_FLOAT(SCS_TELEMETRY_TRUCK_CHANNEL_speed,speed);REG_FLOAT(SCS_TELEMETRY_TRUCK_CHANNEL_engine_rpm,rpm);REG_FLOAT(SCS_TELEMETRY_TRUCK_CHANNEL_fuel,fuel);REG_FLOAT(SCS_TELEMETRY_TRUCK_CHANNEL_fuel_average_consumption,fuel_average);REG_FLOAT(SCS_TELEMETRY_TRUCK_CHANNEL_fuel_range,fuel_range);REG_FLOAT(SCS_TELEMETRY_TRUCK_CHANNEL_cruise_control,cruise);REG_FLOAT(SCS_TELEMETRY_TRUCK_CHANNEL_navigation_distance,navigation_distance);REG_FLOAT(SCS_TELEMETRY_TRUCK_CHANNEL_navigation_time,navigation_time);REG_FLOAT(SCS_TELEMETRY_TRUCK_CHANNEL_navigation_speed_limit,navigation_speed_limit);REG_FLOAT(SCS_TELEMETRY_TRUCK_CHANNEL_odometer,odometer);REG_FLOAT(SCS_TELEMETRY_TRUCK_CHANNEL_brake_air_pressure,brake_air_pressure);REG_FLOAT(SCS_TELEMETRY_TRUCK_CHANNEL_water_temperature,water_temperature);REG_FLOAT(SCS_TELEMETRY_TRUCK_CHANNEL_battery_voltage,battery_voltage);REG_FLOAT(SCS_TELEMETRY_TRUCK_CHANNEL_input_steering,input_steering);REG_FLOAT(SCS_TELEMETRY_TRUCK_CHANNEL_input_throttle,input_throttle);REG_FLOAT(SCS_TELEMETRY_TRUCK_CHANNEL_input_brake,input_brake);REG_FLOAT(SCS_TELEMETRY_TRUCK_CHANNEL_wear_engine,wear_engine);REG_FLOAT(SCS_TELEMETRY_TRUCK_CHANNEL_wear_transmission,wear_transmission);REG_FLOAT(SCS_TELEMETRY_TRUCK_CHANNEL_wear_cabin,wear_cabin);REG_FLOAT(SCS_TELEMETRY_TRUCK_CHANNEL_wear_chassis,wear_chassis);REG_FLOAT(SCS_TELEMETRY_TRUCK_CHANNEL_wear_wheels,wear_wheels);REG_FLOAT(SCS_TELEMETRY_TRAILER_CHANNEL_wear_body,trailer_body);REG_FLOAT(SCS_TELEMETRY_TRAILER_CHANNEL_wear_chassis,trailer_chassis);REG_FLOAT(SCS_TELEMETRY_TRAILER_CHANNEL_wear_wheels,trailer_wheels);REG_FLOAT(SCS_TELEMETRY_TRAILER_CHANNEL_cargo_damage,trailer_cargo_damage);
  p->register_for_channel(SCS_TELEMETRY_TRUCK_CHANNEL_world_placement,SCS_U32_NIL,SCS_VALUE_TYPE_dplacement,SCS_TELEMETRY_CHANNEL_FLAG_none,store_placement,nullptr);p->register_for_channel(SCS_TELEMETRY_TRUCK_CHANNEL_engine_gear,SCS_U32_NIL,SCS_VALUE_TYPE_s32,SCS_TELEMETRY_CHANNEL_FLAG_none,store_s32,&state.gear);p->register_for_channel(SCS_TELEMETRY_TRUCK_CHANNEL_retarder_level,SCS_U32_NIL,SCS_VALUE_TYPE_s32,SCS_TELEMETRY_CHANNEL_FLAG_none,store_s32,&state.retarder_level);p->register_for_channel(SCS_TELEMETRY_TRUCK_CHANNEL_engine_enabled,SCS_U32_NIL,SCS_VALUE_TYPE_bool,SCS_TELEMETRY_CHANNEL_FLAG_none,store_bool,&state.engine);p->register_for_channel(SCS_TELEMETRY_TRUCK_CHANNEL_parking_brake,SCS_U32_NIL,SCS_VALUE_TYPE_bool,SCS_TELEMETRY_CHANNEL_FLAG_none,store_bool,&state.parking_brake);p->register_for_channel(SCS_TELEMETRY_TRUCK_CHANNEL_motor_brake,SCS_U32_NIL,SCS_VALUE_TYPE_bool,SCS_TELEMETRY_CHANNEL_FLAG_none,store_bool,&state.motor_brake);p->register_for_channel(SCS_TELEMETRY_TRUCK_CHANNEL_lblinker,SCS_U32_NIL,SCS_VALUE_TYPE_bool,SCS_TELEMETRY_CHANNEL_FLAG_none,store_bool,&state.left_blinker);p->register_for_channel(SCS_TELEMETRY_TRUCK_CHANNEL_rblinker,SCS_U32_NIL,SCS_VALUE_TYPE_bool,SCS_TELEMETRY_CHANNEL_FLAG_none,store_bool,&state.right_blinker);p->register_for_channel(SCS_TELEMETRY_TRUCK_CHANNEL_hazard_warning,SCS_U32_NIL,SCS_VALUE_TYPE_bool,SCS_TELEMETRY_CHANNEL_FLAG_none,store_bool,&state.hazard);p->register_for_channel(SCS_TELEMETRY_TRUCK_CHANNEL_light_low_beam,SCS_U32_NIL,SCS_VALUE_TYPE_bool,SCS_TELEMETRY_CHANNEL_FLAG_none,store_bool,&state.low_beam);p->register_for_channel(SCS_TELEMETRY_TRUCK_CHANNEL_light_high_beam,SCS_U32_NIL,SCS_VALUE_TYPE_bool,SCS_TELEMETRY_CHANNEL_FLAG_none,store_bool,&state.high_beam);p->register_for_channel(SCS_TELEMETRY_TRUCK_CHANNEL_light_beacon,SCS_U32_NIL,SCS_VALUE_TYPE_bool,SCS_TELEMETRY_CHANNEL_FLAG_none,store_bool,&state.beacon);p->register_for_channel(SCS_TELEMETRY_CHANNEL_game_time,SCS_U32_NIL,SCS_VALUE_TYPE_u32,SCS_TELEMETRY_CHANNEL_FLAG_none,store_u32,&state.game_time);if(game_log)game_log(SCS_LOG_TYPE_message,"VTC Truck Hub telemetry bridge initialized on 127.0.0.1:35055");return SCS_RESULT_ok;}
SCSAPI_VOID scs_telemetry_shutdown(){send_packet("game.exited");if(udp_socket!=INVALID_SOCKET){closesocket(udp_socket);udp_socket=INVALID_SOCKET;}WSACleanup();game_log=nullptr;}
BOOL APIENTRY DllMain(HMODULE,DWORD,LPVOID){return TRUE;}
