import {discordRequest,rulesMessage} from "@/lib/discord";
import {audit,ensureDatabase,platformEnv,randomId} from "@/lib/platform";
const fromHex=(h:string)=>new Uint8Array(h.match(/.{2}/g)?.map(x=>parseInt(x,16))??[]);
type Interaction={type:number;guild_id?:string;channel_id?:string;member?:{user?:{id?:string};permissions?:string};user?:{id?:string};data?:{name?:string;custom_id?:string;components?:Array<{components?:Array<{custom_id?:string;value?:string}>}>}};
const message=(content:string,ephemeral=true)=>Response.json({type:4,data:{content,flags:ephemeral?64:0,allowed_mentions:{parse:[]}}});
export async function POST(request:Request){const cfg=platformEnv(),signature=request.headers.get("x-signature-ed25519"),timestamp=request.headers.get("x-signature-timestamp"),raw=await request.text();if(!cfg.DISCORD_PUBLIC_KEY||!signature||!timestamp)return Response.json({error:"Discord-Signatur fehlt"},{status:401});try{const key=await crypto.subtle.importKey("raw",fromHex(cfg.DISCORD_PUBLIC_KEY),{name:"Ed25519"},false,["verify"]);if(!await crypto.subtle.verify("Ed25519",key,fromHex(signature),new TextEncoder().encode(timestamp+raw)))return Response.json({error:"Signatur ungültig"},{status:401})}catch{return Response.json({error:"Signaturprüfung fehlgeschlagen"},{status:401})}const interaction=JSON.parse(raw) as Interaction;if(interaction.type===1)return Response.json({type:1});await ensureDatabase();const db=platformEnv().DB,name=interaction.data?.name,guildId=interaction.guild_id??"direct";
  if(interaction.type===2&&name==="status")return message("🟢 VTC Truck Hub ist online · API, Abrechnung und Telemetrieempfang sind erreichbar.");
  if(interaction.type===2&&name==="event")return message("📅 Eventinformationen werden über den verbundenen VTC-Truck-Hub-Kalender ausgegeben.");
  if(interaction.type===2&&name==="regeln"){const rows=await db.prepare(`SELECT title,body FROM bot_rules WHERE guild_id=? AND active=1 ORDER BY position`).bind(guildId).all<{title:string;body:string}>(),branding=await db.prepare(`SELECT guild_id AS guildId,rules_title AS rulesTitle,rules_description AS rulesDescription,rules_image_url AS rulesImageUrl,rules_button_label AS rulesButtonLabel FROM discord_guild_branding WHERE guild_id=?`).bind(guildId).first<Record<string,unknown>>();return Response.json({type:4,data:rulesMessage(branding??{guildId},rows.results)});}
  if(interaction.type===3&&interaction.data?.custom_id?.startsWith("rules_accept:")){const userId=interaction.member?.user?.id??interaction.user?.id,config=await db.prepare(`SELECT b.rules_confirm_role_id AS roleId,g.vtc_id AS vtcId FROM discord_guild_branding b JOIN discord_guilds g ON g.guild_id=b.guild_id WHERE b.guild_id=? AND g.enabled=1`).bind(guildId).first<{roleId:string|null;vtcId:string|null}>();if(!userId||!config?.roleId)return message("⚠️ Für diesen Server ist keine Bestätigungsrolle eingerichtet.");try{await discordRequest(`/guilds/${guildId}/members/${userId}/roles/${config.roleId}`,{method:"PUT"});await db.prepare(`INSERT OR IGNORE INTO discord_rule_acceptances (id,guild_id,discord_user_id,role_id) VALUES (?,?,?,?)`).bind(randomId(),guildId,userId,config.roleId).run();await audit("discord.rules.accepted","discord_guild",guildId,userId,{roleId:config.roleId},config.vtcId);return message("✅ Regeln bestätigt. Deine Serverrolle wurde zugeteilt.")}catch{return message("❌ Die Rolle konnte nicht vergeben werden. Bitte prüfe die Bot-Rollenreihenfolge und die Berechtigung ‚Rollen verwalten‘.")}}
  if(interaction.type===2&&name==="ticket")return Response.json({type:9,data:{custom_id:"convoyhub_ticket_create",title:"VTC Truck Hub Support-Ticket",components:[{type:1,components:[{type:4,custom_id:"subject",label:"Betreff",style:1,min_length:3,max_length:100,required:true}]},{type:1,components:[{type:4,custom_id:"message",label:"Wie können wir helfen?",style:2,min_length:10,max_length:1000,required:true}]}]}});
  if(interaction.type===5&&interaction.data?.custom_id==="convoyhub_ticket_create"){const values=Object.fromEntries((interaction.data.components??[]).flatMap(x=>x.components??[]).map(x=>[x.custom_id??"",x.value??""])),next=await db.prepare(`SELECT COALESCE(MAX(number),1000)+1 number FROM support_tickets`).first<{number:number}>(),id=randomId(),discordUserId=interaction.member?.user?.id??interaction.user?.id??"unknown";await db.batch([db.prepare(`INSERT INTO support_tickets (id,number,discord_user_id,discord_channel_id,category,subject) VALUES (?,?,?,?,?,?)`).bind(id,next?.number??1001,discordUserId,interaction.channel_id??null,"Discord",values.subject),db.prepare(`INSERT INTO ticket_messages (id,ticket_id,author_id,author_type,body) VALUES (?,?,?,'discord_user',?)`).bind(randomId(),id,discordUserId,values.message)]);await audit("discord.ticket.created","ticket",id,discordUserId,{guildId,number:next?.number});return message(`✅ Ticket #${next?.number} wurde eröffnet. Das Support-Team meldet sich hier oder über die Plattform.`)}
  return message("🚛 Verfügbare Befehle: /status, /event, /regeln und /ticket.");
}
