"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import ImageUploader from "../../components/ImageUploader";

type Guild=Record<string,any>; type Rule={id:string;guildId:string;title:string;body:string};
export default function DiscordBotAdmin(){
  const [guilds,setGuilds]=useState<Guild[]>([]),[rules,setRules]=useState<Rule[]>([]),[selected,setSelected]=useState(""),[draft,setDraft]=useState<Guild>({}),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{const r=await fetch("/api/admin/discord",{cache:"no-store"});if(r.status===403){location.replace("/admin/login");return}const j=await r.json();if(!r.ok)throw new Error(j.error);setGuilds(j.guilds);setRules(j.rules);if(!selected&&j.guilds[0]){setSelected(j.guilds[0].guildId);setDraft(j.guilds[0])}},[selected]);
  useEffect(()=>{load().catch(e=>setMessage(e.message))},[load]);
  async function act(body:unknown,ok:string){setBusy(true);setMessage("");try{const r=await fetch("/api/admin/discord",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),j=await r.json();if(!r.ok)throw new Error(j.error);setMessage(ok);await load()}catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
  const absolute=(url:string)=>new URL(url,location.origin).href;
  return <main className="workspace-page discord-admin-page"><header className="workspace-head"><div><span className="kicker">PLATTFORM-ADMINISTRATION</span><h1>Discord-Bot</h1><p>Mehrere Server, Regelbestätigung, Rollen, Bilder, Willkommen und Auftragsmeldungen.</p></div><nav><a href="/gruender">Admin-Übersicht</a><a href="/dashboard">Dashboard</a></nav></header>
    {message&&<p className="manage-message" role="status">{message}</p>}
    <div className="discord-admin-layout"><aside className="manage-panel"><div className="manage-head"><h2>Discord-Server</h2><button onClick={()=>{setSelected("");setDraft({rulesTitle:"Regelwerk",rulesButtonLabel:"Regeln bestätigen",welcomeMessage:"Willkommen {user} bei {vtc}!"})}}>+ Server</button></div>{guilds.map(g=><button className={`discord-guild-card ${selected===g.guildId?"selected":""}`} key={g.guildId} onClick={()=>{setSelected(g.guildId);setDraft(g)}}><strong>{g.displayName||g.vtcId||"Discord-Server"}</strong><small>{g.guildId}</small><span>{g.deliveryChannelId?"Auftragskanal aktiv":"Noch nicht vollständig"}</span></button>)}{!guilds.length&&<p>Noch kein Server angelegt.</p>}</aside>
    <section className="manage-panel"><form className="manage-form" onSubmit={(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));act({action:"save",guild:{...draft,...values}},"Discord-Server gespeichert.")}}><h2>{selected?"Server bearbeiten":"Server hinzufügen"}</h2><div className="manage-form-grid"><label>Server-ID<input name="guildId" defaultValue={draft.guildId||""} required pattern="[0-9]{17,20}" /></label><label>Anzeigename<input name="displayName" defaultValue={draft.displayName||""}/></label><label>Speditions-ID<input name="vtcId" defaultValue={draft.vtcId||""}/></label><label>Willkommenskanal<input name="welcomeChannelId" defaultValue={draft.welcomeChannelId||""}/></label><label>Ankündigungskanal<input name="announcementChannelId" defaultValue={draft.announcementChannelId||""}/></label><label>Auftragskanal<input name="deliveryChannelId" defaultValue={draft.deliveryChannelId||""}/></label><label>Regelkanal<input name="rulesChannelId" defaultValue={draft.rulesChannelId||""}/></label><label>Rolle nach Bestätigung<input name="rulesConfirmRoleId" defaultValue={draft.rulesConfirmRoleId||""}/></label><label>Ticket-Kategorie<input name="ticketCategoryId" defaultValue={draft.ticketCategoryId||""}/></label><label>Support-Rolle<input name="supportRoleId" defaultValue={draft.supportRoleId||""}/></label><label>Automatische Rollen (Komma)<input name="autoRoleIds" defaultValue={String(draft.autoRoleIds||"").replace(/[\[\]"]/g,"")}/></label><label>Button-Text<input name="rulesButtonLabel" defaultValue={draft.rulesButtonLabel||"Regeln bestätigen"}/></label></div><label>Willkommensnachricht<input name="welcomeMessage" defaultValue={draft.welcomeMessage||"Willkommen {user} bei {vtc}!"}/></label><label>Regelwerk-Titel<input name="rulesTitle" defaultValue={draft.rulesTitle||"Regelwerk"}/></label><label>Regelwerk-Einleitung<textarea name="rulesDescription" defaultValue={draft.rulesDescription||""}/></label><input type="hidden" name="welcomeImageUrl" value={draft.welcomeImageUrl||""}/><input type="hidden" name="rulesImageUrl" value={draft.rulesImageUrl||""}/><input type="hidden" name="announcementImageUrl" value={draft.announcementImageUrl||""}/><div className="discord-image-grid"><ImageUploader purpose="discord_image" label="Willkommensbild" current={draft.welcomeImageUrl} onUploaded={u=>setDraft(d=>({...d,welcomeImageUrl:absolute(u.url)}))}/><ImageUploader purpose="discord_image" label="Regelwerk-Bild" current={draft.rulesImageUrl} onUploaded={u=>setDraft(d=>({...d,rulesImageUrl:absolute(u.url)}))}/><ImageUploader purpose="discord_image" label="Ankündigungsbild" current={draft.announcementImageUrl} onUploaded={u=>setDraft(d=>({...d,announcementImageUrl:absolute(u.url)}))}/></div><button disabled={busy}>Servereinstellungen speichern</button></form>
      {selected&&<><form className="manage-form discord-tool" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);act({action:"addRule",guildId:selected,title:f.get("title"),body:f.get("body"),position:rules.filter(r=>r.guildId===selected).length},"Regel hinzugefügt.");e.currentTarget.reset()}}><h2>Regelwerk</h2>{rules.filter(r=>r.guildId===selected).map((r,i)=><article key={r.id}><b>{i+1}. {r.title}</b><p>{r.body}</p></article>)}<label>Regeltitel<input name="title" required/></label><label>Regeltext<textarea name="body" required/></label><div><button disabled={busy}>Regel hinzufügen</button><button type="button" disabled={busy} onClick={()=>act({action:"publishRules",guildId:selected},"Regelwerk mit Bestätigungsbutton veröffentlicht.")}>Regelwerk veröffentlichen</button></div></form>
      <form className="manage-form discord-tool" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);act({action:"announce",guildId:selected,message:f.get("message")},"Ankündigung mit Bild gesendet.")}}><h2>Ankündigung senden</h2><label>Nachricht<textarea name="message" required maxLength={4000}/></label><button disabled={busy}>An Discord senden</button></form></>}
    </section></div></main>;
}
