import {apiError,audit,ensureDatabase,getSessionUser,platformEnv,randomId} from "@/lib/platform";

type Body={action?:"create"|"reply"|"close";category?:string;subject?:string;message?:string;ticketId?:string};

export async function GET(request:Request){await ensureDatabase();const user=await getSessionUser(request);if(!user)return apiError("Anmeldung erforderlich",401);const db=platformEnv().DB,tickets=await db.prepare(`SELECT id,number,category,subject,status,priority,created_at AS createdAt,closed_at AS closedAt FROM support_tickets WHERE user_id=? ORDER BY created_at DESC`).bind(user.id).all(),messages=await db.prepare(`SELECT m.id,m.ticket_id AS ticketId,m.author_type AS authorType,m.body,m.created_at AS createdAt FROM ticket_messages m JOIN support_tickets t ON t.id=m.ticket_id WHERE t.user_id=? AND m.internal=0 ORDER BY m.created_at`).bind(user.id).all();return Response.json({tickets:tickets.results,messages:messages.results})}
export async function POST(request:Request){await ensureDatabase();const user=await getSessionUser(request);if(!user)return apiError("Anmeldung erforderlich",401);const body=await request.json() as Body,db=platformEnv().DB;
  if(body.action==="create"){const subject=body.subject?.trim(),message=body.message?.trim();if(!subject||!message)return apiError("Betreff und Nachricht erforderlich");const next=await db.prepare(`SELECT COALESCE(MAX(number),1000)+1 number FROM support_tickets`).first<{number:number}>(),id=randomId();await db.batch([db.prepare(`INSERT INTO support_tickets (id,number,user_id,category,subject) VALUES (?,?,?,?,?)`).bind(id,next?.number??1001,user.id,body.category??"Allgemeine Anfrage",subject),db.prepare(`INSERT INTO ticket_messages (id,ticket_id,author_id,author_type,body) VALUES (?,?,?,'user',?)`).bind(randomId(),id,user.id,message)]);await audit("ticket.created","ticket",id,user.id,{number:next?.number,category:body.category});return Response.json({created:true,id,number:next?.number},{status:201})}
  if(body.action==="reply"&&body.ticketId&&body.message?.trim()){const ticket=await db.prepare(`SELECT id,status FROM support_tickets WHERE id=? AND user_id=?`).bind(body.ticketId,user.id).first<{id:string;status:string}>();if(!ticket)return apiError("Ticket nicht gefunden",404);if(ticket.status==="closed")return apiError("Geschlossenes Ticket zuerst wieder öffnen",409);await db.prepare(`INSERT INTO ticket_messages (id,ticket_id,author_id,author_type,body) VALUES (?,?,?,'user',?)`).bind(randomId(),ticket.id,user.id,body.message.trim()).run();await audit("ticket.replied","ticket",ticket.id,user.id);return Response.json({saved:true})}
  if(body.action==="close"&&body.ticketId){await db.prepare(`UPDATE support_tickets SET status='closed',closed_at=CURRENT_TIMESTAMP WHERE id=? AND user_id=?`).bind(body.ticketId,user.id).run();await audit("ticket.closed","ticket",body.ticketId,user.id);return Response.json({closed:true})}
  return apiError("Ungültige Ticketaktion");
}
