<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType><TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF><UseWindowsForms>true</UseWindowsForms><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable>
    <AssemblyName>VTCTruckHub.Client</AssemblyName><RootNamespace>ConvoyHub.Client</RootNamespace>
    <ApplicationIcon></ApplicationIcon><Version>1.4.0</Version><AssemblyVersion>1.4.0.0</AssemblyVersion><FileVersion>1.4.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\vtc-truck-hub-login.png" />
    <Content Include="plugins\convoyhub_scs.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
</Project>
