const token=process.env.DISCORD_BOT_TOKEN,api=(process.env.CONVOYHUB_API??"http://localhost:3000").replace(/\/$/,""),internalKey=process.env.BOT_INTERNAL_KEY;
if(!token||!internalKey)throw new Error("DISCORD_BOT_TOKEN und BOT_INTERNAL_KEY sind erforderlich");
const discord="https://discord.com/api/v10";let socket,sequence=null,heartbeat;
async function discordRequest(path,options={}){const r=await fetch(discord+path,{...options,headers:{Authorization:`Bot ${token}`,"Content-Type":"application/json",...(options.headers??{})}});if(!r.ok)throw new Error(`Discord ${r.status}: ${await r.text()}`);return r.status===204?null:r.json()}
async function config(guildId){const r=await fetch(`${api}/api/bot/config?guildId=${encodeURIComponent(guildId)}`,{headers:{Authorization:`Bearer ${internalKey}`}});if(!r.ok)throw new Error(`VTC-Truck-Hub-Konfiguration ${r.status}`);return r.json()}
async function interactionReply(interaction,data){await discordRequest(`/interactions/${interaction.id}/${interaction.token}/callback`,{method:"POST",body:JSON.stringify(data)})}
function rulesPayload(guild,rules){const description=rules.length?rules.map((rule,index)=>`**${index+1}. ${rule.title}**\n${rule.body}`).join("\n\n").slice(0,4096):(guild?.rulesDescription||"Für diesen Server wurden noch keine Regeln hinterlegt.");const embed={title:guild?.rulesTitle||"Regelwerk",description,color:0x22d3c5};if(/^https:\/\//i.test(guild?.rulesImageUrl||""))embed.image={url:guild.rulesImageUrl};return {type:4,data:{embeds:[embed],components:[{type:1,components:[{type:2,style:3,label:guild?.rulesButtonLabel||"Regeln bestätigen",custom_id:`rules_accept:${guild?.guildId||"unknown"}`}]}],allowed_mentions:{parse:[]}}}}
async function interactionReceived(interaction){const name=interaction.data?.name,guildId=interaction.guild_id??"direct",ephemeral=content=>({type:4,data:{content,flags:64,allowed_mentions:{parse:[]}}});
  if(interaction.type===2&&name==="status")return interactionReply(interaction,ephemeral("🟢 VTC Truck Hub ist online · API, Abrechnung, Bot und Telemetrieempfang sind erreichbar."));
  if(interaction.type===2&&name==="event")return interactionReply(interaction,ephemeral("📅 Eventinformationen werden über den verbundenen VTC-Truck-Hub-Kalender ausgegeben."));
  if(interaction.type===2&&name==="regeln"){const result=await config(guildId);return interactionReply(interaction,rulesPayload(result.guild,result.rules??[]));}
  if(interaction.type===3&&String(interaction.data?.custom_id||"").startsWith("rules_accept:")){const result=await config(guildId),roleId=result.guild?.rulesConfirmRoleId,userId=interaction.member?.user?.id??interaction.user?.id;if(!roleId||!userId)return interactionReply(interaction,ephemeral("⚠️ Für diesen Server ist noch keine Bestätigungsrolle eingerichtet."));try{await discordRequest(`/guilds/${guildId}/members/${userId}/roles/${roleId}`,{method:"PUT"});await fetch(`${api}/api/bot/events`,{method:"POST",headers:{Authorization:`Bearer ${internalKey}`,"Content-Type":"application/json"},body:JSON.stringify({type:"rules.accepted",guildId,discordUserId:userId,roleId})});return interactionReply(interaction,ephemeral("✅ Regeln bestätigt. Deine Serverrolle wurde zugeteilt."))}catch(error){console.error("Regelrolle:",error);return interactionReply(interaction,ephemeral("❌ Die Rolle konnte nicht vergeben werden. Bitte prüfe die Bot-Rollenreihenfolge und die Berechtigung ‚Rollen verwalten‘."))}}
  if(interaction.type===2&&name==="ticket")return interactionReply(interaction,{type:9,data:{custom_id:"convoyhub_ticket_create",title:"VTC Truck Hub Support-Ticket",components:[{type:1,components:[{type:4,custom_id:"subject",label:"Betreff",style:1,min_length:3,max_length:100,required:true}]},{type:1,components:[{type:4,custom_id:"message",label:"Wie können wir helfen?",style:2,min_length:10,max_length:1000,required:true}]}]}});
  if(interaction.type===5&&interaction.data?.custom_id==="convoyhub_ticket_create"){const values=Object.fromEntries((interaction.data.components??[]).flatMap(row=>row.components??[]).map(field=>[field.custom_id,field.value])),discordUserId=interaction.member?.user?.id??interaction.user?.id??"unknown",r=await fetch(`${api}/api/bot/events`,{method:"POST",headers:{Authorization:`Bearer ${internalKey}`,"Content-Type":"application/json"},body:JSON.stringify({type:"ticket.created",guildId,discordUserId,discordChannelId:interaction.channel_id,category:"Discord",subject:values.subject,message:values.message})});if(!r.ok)throw new Error(`Ticket konnte nicht gespeichert werden: ${r.status}`);const ticket=await r.json();return interactionReply(interaction,ephemeral(`✅ Ticket #${ticket.number} wurde eröffnet. Das Support-Team meldet sich über VTC Truck Hub.`));}
  return interactionReply(interaction,ephemeral("🚛 Verfügbare Befehle: /status, /event, /regeln und /ticket."));}
async function memberAdded(member){const guildId=member.guild_id,userId=member.user?.id;if(!guildId||!userId)return;const {guild}=await config(guildId);if(!guild?.enabled)return;const roles=JSON.parse(guild.autoRoleIds??"[]");for(const role of roles)await discordRequest(`/guilds/${guildId}/members/${userId}/roles/${role}`,{method:"PUT"});if(guild.welcomeChannelId){const content=String(guild.welcomeMessage??"Willkommen {user} bei {vtc}!").replaceAll("{user}",`<@${userId}>`).replaceAll("{vtc}",guild.displayName??guild.vtcId??"VTC Truck Hub"),payload={content,allowed_mentions:{users:[userId]}};if(/^https:\/\//i.test(guild.welcomeImageUrl||""))payload.embeds=[{image:{url:guild.welcomeImageUrl},color:0x22d3c5}];await discordRequest(`/channels/${guild.welcomeChannelId}/messages`,{method:"POST",body:JSON.stringify(payload)})}}
function identify(){socket.send(JSON.stringify({op:2,d:{token,intents:3,properties:{os:"windows",browser:"convoyhub",device:"convoyhub"}}}))}
function connect(){socket=new WebSocket("wss://gateway.discord.gg/?v=10&encoding=json");socket.addEventListener("message",async event=>{const packet=JSON.parse(event.data);if(packet.s!==null&&packet.s!==undefined)sequence=packet.s;if(packet.op===10){clearInterval(heartbeat);heartbeat=setInterval(()=>socket.send(JSON.stringify({op:1,d:sequence})),packet.d.heartbeat_interval);identify();return}if(packet.op===7){socket.close();return}if(packet.op===0&&packet.t==="READY")console.log(`VTC Truck Hub Bot online als ${packet.d.user.username}`);if(packet.op===0&&packet.t==="GUILD_MEMBER_ADD")try{await memberAdded(packet.d)}catch(error){console.error("Willkommensablauf:",error)}if(packet.op===0&&packet.t==="INTERACTION_CREATE")try{await interactionReceived(packet.d)}catch(error){console.error("Discord-Interaktion:",error)}});socket.addEventListener("close",()=>{clearInterval(heartbeat);setTimeout(connect,3000)});socket.addEventListener("error",error=>console.error("Discord Gateway:",error))}
connect();
